const fs = require('fs');
const path = require('path');

const loadAdapter = () => {
  const source = fs.readFileSync(path.join(__dirname, '..', 'content-scripts/content-zai.js'), 'utf8');
  // eslint-disable-next-line no-eval
  eval(source);
};

const markVisible = () => {
  document.querySelectorAll('*').forEach((node) => {
    node.getClientRects = () => [{ width: 100, height: 40 }];
  });
};

describe('Z.ai response extraction', () => {
  beforeEach(() => {
    document.body.replaceChildren();
    delete window.zaiContentScriptLoaded;
    delete window.__zaiAdapter;
    window.BaseLLMAdapter = class {
      handleMessage() { return false; }
      _cleanup() {}
    };
    window.ContentUtils = {
      sleep: (ms) => new Promise((resolve) => setTimeout(resolve, Math.min(ms, 1))),
      buildInlineHtml: (node) => node.outerHTML
    };
    window.AnswerContentClassifier = require('../shared/answer-content-classifier');
    global.chrome = {
      runtime: {
        onMessage: { addListener: jest.fn() },
        sendMessage: jest.fn()
      }
    };
    loadAdapter();
  });

  afterEach(() => {
    delete global.chrome;
    delete window.BaseLLMAdapter;
    delete window.ContentUtils;
    delete window.AnswerContentClassifier;
    delete window.__zaiAdapter;
    delete window.zaiContentScriptLoaded;
  });

  test('prefers the real chat-assistant markdown over the Generated by AI footer', () => {
    document.body.innerHTML = `
      <div id="message-user-1" class="chat-user markdown-prose">Пользовательский запрос</div>
      <div id="message-assistant-1-start" class="chat-assistant w-full min-w-full markdown-prose">
        Полный ответ модели Z.ai, который должен попасть в карточку результатов.
      </div>
      <footer><div class="prose">Generated by AI.</div></footer>
    `;
    markVisible();

    const result = window.__zaiAdapter.readLatestResponse();
    expect(result.text).toContain('Полный ответ модели Z.ai');
    expect(result.text).not.toContain('Generated by AI');
  });

  test('selects the latest assistant turn after a follow-up even across selector layers', () => {
    document.body.innerHTML = `
      <main id="chat-messages">
        <div id="message-old-start" class="chat-assistant markdown-prose">Previous Z.ai answer</div>
        <div id="message-user-2" class="chat-user markdown-prose">Follow-up prompt</div>
        <section data-role="assistant">Latest Z.ai answer</section>
        <div id="message-user-3" class="chat-user markdown-prose">Trailing user draft</div>
      </main>
    `;
    markVisible();

    const candidates = window.__zaiAdapter.responseCandidates();
    expect(candidates.map((node) => node.textContent.trim())).toEqual([
      'Previous Z.ai answer',
      'Latest Z.ai answer'
    ]);
    expect(window.__zaiAdapter.readLatestResponse().text).toBe('Latest Z.ai answer');
  });

  test('never treats the provider disclaimer as an answer', () => {
    document.body.innerHTML = '<footer><div class="prose">Generated by AI.</div></footer>';
    expect(window.__zaiAdapter.readLatestResponse().text).toBe('');
    expect(window.__zaiAdapter.isRejectedResponseText('Generated by AI.')).toBe(true);
  });

  test('returns a generated answer when trailing prompt scaffolding is a later DOM candidate', () => {
    document.body.innerHTML = `
      <main id="chat-messages">
        <div id="message-answer-start">Полный сгенерированный ответ Z.AI.</div>
        <section data-testid="assistant-scaffolding">Refer to the following content</section>
      </main>`;
    markVisible();

    const result = window.__zaiAdapter.readLatestResponse();
    expect(result.text).toBe('Полный сгенерированный ответ Z.AI.');
    expect(window.__zaiAdapter.isRejectedResponseText('Refer to the following content')).toBe(true);
  });

  test('does not admit a user message through the broader message-start selector', () => {
    document.body.innerHTML = `
      <div id="message-answer-start">Generated answer</div>
      <div id="message-user-start" class="chat-user">Later user prompt</div>`;
    markVisible();

    expect(window.__zaiAdapter.readLatestResponse().text).toBe('Generated answer');
  });

  test('requires a six-second quiet window before treating stable text as complete', () => {
    const source = fs.readFileSync(path.join(__dirname, '..', 'content-scripts', 'content-zai.js'), 'utf8');
    expect(source).toContain('const ZAI_STABLE_TEXT_MS = 6000;');
    expect(source).toContain('Date.now() - stableSince >= ZAI_STABLE_TEXT_MS');
    expect(source).toContain('stableTextMs: ZAI_STABLE_TEXT_MS');
  });
});
